version: '3'
services:
  app:
    image: mds
    ports:
      - "8000:80"
    volumes:
      - .:/src
    depends_on:
      - migration
    environment:
      - DB_HOST=db
      - DB_USER=mds
    command: /env/bin/uvicorn --host 0.0.0.0 --port 80 mds.app:app --reload
  migration:
    build: .
    image: mds
    volumes:
      - .:/src
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=mds
    command: /env/bin/alembic upgrade head
  db:
    image: postgres
    environment:
      - POSTGRES_USER=mds
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
