[tool.poetry]
name = "mds"
version = "1.1.1-alpha"
description = "DCFS Metadata Service"
authors = ["CTDS UChicago <cdis@uchicago.edu>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.7"
fastapi = "^0.44.1"
uvicorn = "^0.10.8"
gunicorn = "^20.0"
gino = "^0.8.5"
alembic = "^1.3"
psycopg2-binary = "^2.8"

[tool.poetry.dev-dependencies]
pytest = "^5.3"
pytest-cov = "^2.8"
requests = "^2.22"

[tool.poetry.plugins."mds.modules"]
"query" = "mds.query"
"maintain" = "mds.maintain"
"index" = "mds.index"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
