name: docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to GitHub Packages
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: uc-cdis/metadata-service/mds
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        tag_names: true
    - name: Publish to quay.io
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: cdis/metadata-service
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}
        registry: quay.io
        tag_names: true
